# Generated by Django 4.2 on 2023-05-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'Черновик'), ('PB', 'Опубликованно')], default='DR', max_length=2),
        ),
    ]
